name: Documentation
on:
  push:
    branches:
      - main
      - actions
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Build documentation
      run: |
          npm install
          npm run docs
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
